# Comparison of spectrum between eNATL60 outputs and Alitka Satellite : method gonzag cloud on one track

Requisites :
 - git clone https://github.com/auraoupa/gonzag_cloud
 
 


In [35]:
import sys,os
from os import getenv
import warnings
warnings.filterwarnings("ignore")

In [36]:
GONZAG_CLOUD_DIR = '/home/jovyan/gonzag_cloud' ; 
sys.path.append(GONZAG_CLOUD_DIR)
import gonzag as gzc


In [37]:
import xarray as xr
import intake
import gcsfs
import os
import pandas as pd
import matplotlib.pyplot as plt

# With gonzag_cloud

In [38]:
model = 'eNATL60'
region = '1'
season = 'fma'
surf='surface_hourly'
name_mod = model+'-Region'+region+'-'+season
name_ssh_mod = 'sossheig'
name_lsm_mod = 'tmask' 
name_lat_mod = 'lat'
name_lon_mod = 'lon'
name_time_mod = 'time_counter'
l_griddist = False
period_mod = ['2010-02-01','2010-04-30']

In [39]:
name_sat= 'Altika'
tag_sat_catalog = 'al'
name_ssh_sat='sla_unfiltered'
name_time_sat='time'
period_sat = ['2014-02-01','2014-04-30'] #should cover the same period of a different year if needed

In [40]:

gcs = gcsfs.GCSFileSystem(requester_pays=True)

cat = intake.open_catalog('../../SWOT-AdAC/catalog.yaml')
dsmod = cat[model](region=region,depth=surf, season=season).to_dask()

In [41]:
dsmod

<xarray.Dataset>
Dimensions:        (time_counter: 2136, x: 611, y: 763)
Coordinates: (12/15)
    depth          (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1f            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1t            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1u            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1v            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e2f            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    ...             ...
    lat            (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    lon            (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    nav_lat        (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    nav_lon        (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    time_centered  (time_counter) datetime64[ns] dask.array<chunksize=(72,), meta=np.ndarray>
  * time_counter   (time_counter) datetime64[ns] 2010-02-01T00:30:00 ... 2010...
Dimensions without coordinates: x, y
Data variables: (12/13)
    fmask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>
    qt_oce         (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    somecrty       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sometauy       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sosaline       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sossheig       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    ...             ...
    sowaflup       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sozocrtx       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sozotaux       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    tmask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>
    umask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>
    vmask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>

In [42]:
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/altimetry.yaml")
dssat  = cat[tag_sat_catalog].to_dask()

In [43]:
dssat

<xarray.Dataset>
Dimensions:         (time: 34340107)
Coordinates:
    latitude        (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    longitude       (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
  * time            (time) datetime64[ns] 2013-03-14T05:44:50.445185 ... 2015...
Data variables:
    cycle           (time) int16 dask.array<chunksize=(34340107,), meta=np.ndarray>
    dac             (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    lwe             (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    mdt             (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    ocean_tide      (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    sla_filtered    (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    sla_unfiltered  (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    track           (time) int16 dask.array<chunksize=(34340107,), meta=np.ndarray>
Attributes: (12/24)
    Conventions:               CF-1.6
    Metadata_Conventions:      Unidata Dataset Discovery v1.0
    cdm_data_type:             Swath
    comment:                   Sea surface height measured by altimeters refe...
    contact:                   servicedesk.cmems@mercator-ocean.eu
    creator_email:             servicedesk.cmems@mercator-ocean.eu
    ...                        ...
    software_version:          6.2_DUACS_DT2018_baseline
    source:                    Altika measurements
    ssalto_duacs_comment:      The reference mission used for the altimeter i...
    standard_name_vocabulary:  NetCDF Climate and Forecast (CF) Metadata Conv...
    summary:                   SSALTO/DUACS Delayed-Time Level-3 sea surface ...
    title:                     DT Altika Global Ocean Along track SSALTO/DUAC...

In [44]:
ModelGrid = gzc.ModGrid( dsmod, period_mod, name_lon_mod, name_lat_mod , name_time_mod, dsmod, name_lsm_mod )



 *** what we use to define model land-sea mask:
    => "tmask" in dataset 

 *** Skipping computation of angle distortion of the model grid! ("-D" option not invoked)...

 *** About model gridded (source) domain:
     * shape =  (763, 611)
     * horizontal resolution:  0.016657295  degrees or  1.8507920147292316  km
     * Is this a global domain w.r.t longitude:  False
       ==> this is a regional domain
       ==> working in the [0:360] frame...
     * lon_min, lon_max =  281.97 292.16
     * lat_min, lat_max =  30.0 39.99
     * should we pay attention to possible STRONG local distorsion in the grid:  False
     * number of time records of interest for the interpolation to come:  2112
       ==> time record dates: 2010-02-01 to 2010-04-30, included



In [45]:
SatelliteTrack = gzc.SatTrack( dssat, period_sat, name_time_sat, name_ssh_sat, domain_bounds=ModelGrid.domain_bounds, l_0_360=ModelGrid.l360 )

 *** [SatTrack()] Analyzing the time vector in dataset ...

 *** About satellite track (target) domain:
     * number of time records of interest for the interpolation to come:  10225
       ==> time record indices: 14883510 to 19033581, included

       separated in 86 tracks


In [46]:
print(ModelGrid.time)

['2010-02-01T00:30:00.000000000' '2010-02-01T01:30:00.000000000'
 '2010-02-01T02:30:00.000000000' ... '2010-04-30T21:30:00.000000000'
 '2010-04-30T22:30:00.000000000' '2010-04-30T23:30:00.000000000']


In [47]:
print(ModelGrid.lat.values)

[[29.996578 29.99662  29.99666  ... 30.02353  30.023575 30.02362 ]
 [30.01064  30.010681 30.010723 ... 30.037706 30.037752 30.037798]
 [30.024696 30.024738 30.02478  ... 30.05188  30.051926 30.051973]
 ...
 [39.75571  39.756042 39.756374 ... 39.970264 39.97063  39.970997]
 [39.767307 39.76764  39.76797  ... 39.982243 39.98261  39.982975]
 [39.7789   39.779232 39.779564 ... 39.994217 39.994583 39.994953]]


In [48]:
print(ModelGrid.lon.values)

[[281.99213 282.0088  282.02545 ... 292.12457 292.14124 292.1579 ]
 [281.9921  282.00876 282.02542 ... 292.1245  292.14117 292.15784]
 [281.99207 282.00873 282.0254  ... 292.12445 292.1411  292.15778]
 ...
 [281.85104 281.86768 281.88428 ... 291.96457 291.98123 291.99786]
 [281.85065 281.86728 281.88388 ... 291.9641  291.98077 291.99744]
 [281.85028 281.86688 281.88348 ... 291.96368 291.98032 291.99698]]


In [49]:
print(ModelGrid.domain_bounds)

[29.996578, 281.96854, 39.994953, 292.1579]


In [50]:
print(SatelliteTrack.time)

['2014-02-02T23:14:13.207444000' '2014-02-02T23:14:14.187444000'
 '2014-02-02T23:14:15.167444000' ... '2014-04-29T23:14:02.891097000'
 '2014-04-29T23:14:03.871097000' '2014-04-29T23:14:04.851097000']


In [51]:
print(SatelliteTrack.lat.values)

[39.973308 39.915793 39.858275 ... 30.154056 30.096212 30.038367]


In [52]:
print(SatelliteTrack.lon.values)

[289.681787 289.662966 289.644169 ... 287.489777 287.474097 287.458431]


In [53]:
print(SatelliteTrack.size)

10225


In [54]:
print(SatelliteTrack.keepit)

(array([  93133,   93134,   93135, ..., 4148222, 4148223, 4148224]),)


In [55]:
import time ; # to report execution speed of certain parts of the code...
import pandas as pd
import numpy as np
from gonzag.config import ldebug, ivrb, nb_talk, l_plot_meshes, deg2km, rfactor, search_box_w_km, l_save_track_on_model_grid, l_plot_meshes, rmissval
from gonzag.utils  import *
from gonzag.bilin_mapping import BilinTrack


In [56]:
MG=ModelGrid
ST=SatelliteTrack 
one_track=0

In [57]:
jt1=ST.index_tracks[one_track][0]
jt2=ST.index_tracks[one_track][1]

(Nj,Ni) = MG.shape

d_found_km = rfactor*MG.HResDeg*deg2km
np_box_radius = SearchBoxSize( MG.HResDeg*deg2km, search_box_w_km )
Nt = jt2 - jt1 ; # number of satellit observation point to work with here...
if_talk = Nt//nb_talk

In [58]:
print(d_found_km,np_box_radius,Nt)

1.3880940110469238 135 171


In [59]:
print(jt1,jt2)

168 339


In [60]:
BT = BilinTrack( ST.lat[jt1:jt2], ST.lon[jt1:jt2], MG.lat, MG.lon, src_grid_local_angle=MG.xangle, k_ew_per=MG.EWPer, rd_found_km=d_found_km, np_box_r=np_box_radius, freq_talk=if_talk )


In [61]:
import xarray as xr
import sys
import glob
import numpy as nmp
import pandas as pd

import matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

import cartopy.crs as ccrs
import cartopy.feature as cfeature
import cartopy.mpl.ticker as cticker

%matplotlib inline


In [62]:
ST.time[jt1:jt2]

array(['2014-02-03T10:27:51.939834000', '2014-02-03T10:27:52.919834000',
       '2014-02-03T10:27:53.899834000', '2014-02-03T10:27:54.879834000',
       '2014-02-03T10:27:55.859834000', '2014-02-03T10:27:56.839834000',
       '2014-02-03T10:27:57.819834000', '2014-02-03T10:27:58.799833000',
       '2014-02-03T10:27:59.779834000', '2014-02-03T10:28:00.759834000',
       '2014-02-03T10:28:01.739834000', '2014-02-03T10:28:02.719834000',
       '2014-02-03T10:28:03.699834000', '2014-02-03T10:28:04.679834000',
       '2014-02-03T10:28:05.659834000', '2014-02-03T10:28:06.639834000',
       '2014-02-03T10:28:07.619834000', '2014-02-03T10:28:08.599834000',
       '2014-02-03T10:28:09.579834000', '2014-02-03T10:28:10.559834000',
       '2014-02-03T10:28:11.539834000', '2014-02-03T10:28:12.519834000',
       '2014-02-03T10:28:13.499834000', '2014-02-03T10:28:14.479833000',
       '2014-02-03T10:28:15.459833000', '2014-02-03T10:28:16.439834000',
       '2014-02-03T10:28:17.419834000', '2014-02-03

In [63]:
        vssh_m_np = nmp.zeros(Nt) ; vssh_m_np[:] = rmissval; # vector to store the model data interpolated in time and space (nearest-point) on the satellite track...
        vssh_m_bl = nmp.zeros(Nt) ; vssh_m_bl[:] = rmissval; # vector to store the model data interpolated in time and space (bilinear) on the satellite track...
        vdistance = nmp.zeros(Nt)
    
        # Time increment on the satellite time:
        ktm1   = 0   ; ktm2   = 0
        ktm1_o = -10 ; ktm2_o = -10


In [64]:
from gonzag.io   import GetModel2DVar, GetSatSSH

In [65]:
        vssh_s = GetSatSSH( ST.file, name_ssh_sat,  kt1=jt1, kt2=jt2-1)

In [66]:
lat_m = nmp.zeros(Nt) ; lat_m[:] = rmissval;
lon_m = nmp.zeros(Nt) ; lon_m[:] = rmissval;
I1=nmp.zeros(Nt) ; I1[:]=rmissval;
J1=nmp.zeros(Nt) ; J1[:]=rmissval;
KT=nmp.zeros(Nt) ; J1[:]=rmissval;
M1=nmp.zeros(Nt) ; M1[:]=rmissval;
M2=nmp.zeros(Nt) ; M2[:]=rmissval;
for jt in range(jt1,jt2):
    print(jt)
    itt = ST.time[jt]
    year_sat=pd.to_datetime(itt).year
    date_model=pd.Series(MG.time)
    date_model_satyear=date_model.apply(lambda dt: dt.replace(year=year_sat))
    kt = ktm1
    KT[jt-jt1]=kt
    while not (date_model_satyear[kt]<=itt and date_model_satyear[kt+1]>itt): kt=kt+1
    ktm1 = kt ; ktm2 = kt+1
    print(itt,kt,MG.time[kt])
    if (ktm1>ktm1_o) and (ktm2>ktm2_o):
        if (ktm1_o == -10) or (ktm1 > ktm2_o):
            Xm1 = GetModel2DVar( MG.file, name_ssh_mod, kt=ktm1 )
        else:
            Xm1[:,:] = Xm2[:,:]
        Xm2 = GetModel2DVar( MG.file, name_ssh_mod, kt=ktm2 )
        Xa = (Xm2 - Xm1) / float((MG.time[ktm2] - MG.time[ktm1] )/ np.timedelta64(1, 's'))
    Xm = Xm1[:,:] + Xa[:,:]*float((itt - date_model_satyear[ktm1])/ np.timedelta64(1, 's'))
    [ [j1,i1],[j2,i2],[j3,i3],[j4,i4] ] = BT.SM[jt-jt1,:,:]
    [w1, w2, w3, w4]                    = BT.WB[jt-jt1,:]
    Sm = MG.mask[j1,i1] + MG.mask[j2,i2] + MG.mask[j3,i3] + MG.mask[j4,i4]
    if Sm == 4 and j1 > 0 and i1 > 0:
        I1[jt-jt1]=i1
        J1[jt-jt1]=j1
        M1[jt-jt1]=Xm1[j1,i1].values
        M2[jt-jt1]=Xm2[j1,i1].values
        vssh_m_np[jt-jt1] = Xm[j1,i1] ; # Nearest-point "interpolation"
        Sw = nmp.sum([w1, w2, w3, w4])
        if abs(Sw-1.)> 0.001:
            if ivrb>0: print('    FLAGGING MISSING VALUE at jt = '+str(jt)+' !!!')
        else:
            vssh_m_bl[jt-jt1] = w1*Xm[j1,i1] + w2*Xm[j2,i2] + w3*Xm[j3,i3] + w4*Xm[j4,i4]
            
    ktm1_o = ktm1 ; ktm2_o = ktm2


168
2014-02-03T10:27:51.939834000 57 2010-02-03T09:30:00.000000000
169
2014-02-03T10:27:52.919834000 57 2010-02-03T09:30:00.000000000
170
2014-02-03T10:27:53.899834000 57 2010-02-03T09:30:00.000000000
171
2014-02-03T10:27:54.879834000 57 2010-02-03T09:30:00.000000000
172
2014-02-03T10:27:55.859834000 57 2010-02-03T09:30:00.000000000
173
2014-02-03T10:27:56.839834000 57 2010-02-03T09:30:00.000000000
174
2014-02-03T10:27:57.819834000 57 2010-02-03T09:30:00.000000000
175
2014-02-03T10:27:58.799833000 57 2010-02-03T09:30:00.000000000
176
2014-02-03T10:27:59.779834000 57 2010-02-03T09:30:00.000000000
177
2014-02-03T10:28:00.759834000 57 2010-02-03T09:30:00.000000000
178
2014-02-03T10:28:01.739834000 57 2010-02-03T09:30:00.000000000
179
2014-02-03T10:28:02.719834000 57 2010-02-03T09:30:00.000000000
180
2014-02-03T10:28:03.699834000 57 2010-02-03T09:30:00.000000000
181
2014-02-03T10:28:04.679834000 57 2010-02-03T09:30:00.000000000
182
2014-02-03T10:28:05.659834000 57 2010-02-03T09:30:00.00000

In [67]:
print(KT)

[ 0. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57.
 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57.
 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57.
 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57.
 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57.
 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57.
 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57. 57.
 57. 57. 57. 57. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58.
 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58. 58.
 58. 58. 58. 58. 58. 58. 58. 58. 58.]


In [ ]:
Xm1 = GetModel2DVar( MG.file, name_ssh_mod, kt=57 )
Xm2 = GetModel2DVar( MG.file, name_ssh_mod, kt=58 )
Xm3 = GetModel2DVar( MG.file, name_ssh_mod, kt=59 )
fig=plt.figure(figsize=[21,5])
ax = plt.subplot(131,projection=ccrs.PlateCarree())
m=ax.pcolormesh(Xm1)
ax = plt.subplot(132,projection=ccrs.PlateCarree())
ax.pcolormesh(Xm2)
ax = plt.subplot(133,projection=ccrs.PlateCarree())
ax.pcolormesh(Xm3)
